[images]
remote_images = ["https://source.unsplash.com/**", "https://images.unsplash.com/**", "https://ext.same-assets.com/**", "https://ugc.same-assets.com/**"]

[build]
command = "bunx prisma format && bunx prisma generate && bunx prisma db push && bun run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"
